sudo: false
language: android
android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    - extra-google-google_play_services
    - addon-google_apis-google-23
script:
  - ./gradlew build assembleDebug
notifications:
  slack: rcos:WWNMphR4ouhl7e4aI5C10izZ#shuttle-tracking
